### ISSUE TITLE
problems when using `workon` inside `.env` file

### ISSUE THREAD

**Issue by aleprovencio** [kennethreitz/autoenv#101]
Upon changing directory to the project's root where the `.env` lives, the file is sourced and seem to work fine, but when changing to directories inside the project, `autoenv_cd dir` will not work (no error messages) while `builtin cd dir` works normally.

**Comment by aleprovencio** [comment]
What does work is to call like this: 
`source ~/.virtualenvs/$PROJECT_NAME/bin/activate`

**Comment by kennethreitz** [comment]
`workon` should behave properly, but that is also a perfectly acceptable solution.

**Comment by aleprovencio** [comment]
Agreed.
