### ISSUE TITLE
cd hangs when entering directory from directory with part of its name

### ISSUE THREAD

**Issue by vpzomtrrfrt** [kennethreitz/autoenv#104]
I have a folder with a `.env` file in it that sets an environment variable.  It works fine, but if I cd into it from a certain other folder it just hangs.  It seems to be related to the fact that the other folder's name is the first part of the name of the folder with the `.env`.

**Comment by vpzomtrrfrt** [comment]
Actually, it doesn't even have to have a `.env` file.  The plugin itself breaks this.

**Comment by dasJ** [comment]
So I assume you have something like this:
```
/home/user/something/a
/home/user/asd
```
And being in the first directory you cd into the second directory and it crashes?
