### ISSUE TITLE
Rewrite a reverse search from the current working directory back to the filesystem’s root directory for .env files

### ISSUE THREAD

**Issue by siriniok** [kennethreitz/autoenv#107]
I have a trouble with [last-working-dir](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/last-working-dir/last-working-dir.plugin.zsh) zsh plugin. This plugin absolutely doesn't work with `autoenv` because it overwrites the last working directory here: [activate.sh#L29](https://github.com/kennethreitz/autoenv/blob/master/activate.sh#L29).

The `autoenv` overwrites last working directory to `/home` after each `cd` call, so all new terminal instances will always open with `/home` working directory.

I have a temporary fix:
```sh
autoenv_cd() {
  if builtin cd "$@"
  then
    cache_file="$HOME/.oh-my-zsh/cache/last-working-dir"
    last_working_dir="`cat "$cache_file"`"

    autoenv_init

    echo $last_working_dir >| "$cache_file"

    return 0
  else
    return $?
  fi
}
``` 

But I think we should completely rewrite this place: [activate.sh#L22](https://github.com/kennethreitz/autoenv/blob/master/activate.sh#L22) in such way:
```ruby
require 'pathname'

def config_dir(dir = Pathname.new("."))
  app_config_dir = dir + ".myappconfigfolder"
  if dir.children.include?(app_config_dir)
    app_config_dir.expand_path
  else
    return nil if dir.expand_path.root?
    config_dir(dir.parent)
  end
end
```
[Source](https://www.practicingruby.com/articles/configurable-applications-2)

This code in Ruby does a reverse search from the current working directory back to the filesystem’s root directory. As for me, it is the best way to solve this issue, but I haven't enough experience to implement this in the shell script.

**Comment by dasJ** [comment]
I think this is already fixed. autoenv is currently searching until the mountpoint.
