### ISSUE TITLE
customizable .env filename

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/autoenv#109]
something akin to `$AUTOENV_SCRIPTNAME` or something

related: https://github.com/kennethreitz/autoenv/issues/50

**Comment by dasJ** [comment]
Implemented, just set `AUTOENV_ENV_FILENAME`, as the README states.

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by kunalbhagawati** [comment]
On OSX Yosemite, this does not seem to be working

My .zshrc file:
```
# some stuff

export AUTOENV_ENV_FILENAME=".autoenv"
source /usr/local/bin/activate.sh
```

**Comment by dasJ** [comment]
@kunalbhagawati Does it work with the current master?
