### ISSUE TITLE
New mountpoint logic requires GNU coreutils on OSX

### ISSUE THREAD

**Issue by kergoth** [kennethreitz/autoenv#114]
Darwin's stat uses -f, not -c, for the format string, and has no format string for the mount point at all. While some macs will have coreutils installed via homebrew, and as such will have gstat available, that won't be the case for all. I expect, unless there's a way to get at the mountpoint on the mac I'm not familiar with, it might be best to revert to the old behavior on such systems, i.e. something like this, perhaps?

```bash
case $OSTYPE in
    darwin*)
        _home="$(dirname "$HOME")"
        _mountcheck () {
            [[ "$PWD" != "/" && "$PWD" != "$_home" ]]
        }
        ;;
    *)
        _mountpoint="`stat -c '%m' \"$PWD\"`"
        _mountcheck () {
            [[ "$PWD" != "$_mountpoint" ]]
        }
        ;;
esac

_files=( $(
    while _mountcheck; do
```

Thanks! Love the project, quite handy.

**Comment by davidjb** [comment]
Just hit this as well (Mac OS X 10.11).  An option for Mac could be to use the output of `df "$PWD"` and extract the value of the final field, "Mounted on" eg:
```
~:$ df "$PWD" | awk 'END{print $NF}'
/
~:$ cd /Volumes/media/docs
docs:$ df "$PWD" | awk 'END{print $NF}'
/Volumes/media
```

**Comment by dasJ** [comment]
@davidjb I really like it that way, but can we be sure that we'll always have an awk?

**Comment by dasJ** [comment]
Can anyone test #115 on darwin?

**Comment by davidjb** [comment]
@dasJ On OSX there should always be AWK; at least judging from Apple's docs (https://developer.apple.com/library/mac/documentation/OpenSource/Conceptual/ShellScripting/Howawk-ward/Howawk-ward.html).   Might want a fallback of `/` in case awk has been removed for any reason.

#115 works for me on OSX, but I think it'd be best to have a conditional between Darwin and other environments; df output can differ between platforms/versions and awk may not be present either. Perhaps use `stat` for non-Darwin?

**Comment by dasJ** [comment]
@davidjb I rewrote #115 and it works on Linux. Does it work on darwin as well?

**Comment by davidjb** [comment]
Tested and works for me, thanks @dasJ
