### ISSUE TITLE
cd'ing into subdirectories executes parent .env scripts

### ISSUE THREAD

**Issue by shammellee** [kennethreitz/autoenv#123]
example directory structure…

    project/
    -- .env # this file echoes 'foo'
    -- subdirectory_1/
        -- .env # this file echoes 'bar'
        -- subdirectory_2/
            -- .env # this file echoes 'baz'

if i `cd` into `project` i get…

    foo

if i `cd` into `project/subdirectory_1` i get…

    foo
    bar

if i `cd` into `project/subdirectory_1/subdirectory_2` i get…

    foo
    bar
    baz

how come the .env of the directory i `cd` into isn't the only script that executes?
also, why do parent scripts execute even if the subdirectory i `cd` into doesn't have a .env file?

**Comment by dasJ** [comment]
autoenv automatically searches for .env files in parent directories: https://github.com/kennethreitz/autoenv/blob/master/activate.sh#L15

This allows you to nest the .env files at will.

Parent .env files execute so you can go into any directory. I'm a go developer, so I need to have GOPATH set. Assuming this structure:
```
myproject/
myproject/bin/
myproject/src/
myproject/src/awesome.go
myproject/.env
```
I can just cd to `myproject/src` and have my `GOPATH` set without needing to think about cd'ing to `myproject/`.

I hope this clears up the autoenv behaviour.
---
One thing that might worth changing is the .env file order. Currently, autoenv walks up to the mountpoint, and executes every .env file it finds, beginning with the bottom one. It might be wiser to do it in the opposite way so you can have generic variables/autoenvs/... in higher directories and project-specific variables in the project directory.

**Comment by shammellee** [comment]
i see. that makes sense.

thanks
