### ISSUE TITLE
`cd //` results in infinite loop

### ISSUE THREAD

**Issue by greg9q** [kennethreitz/autoenv#125]
Using version 0.1.0 on my Mac. `cd //` gets caught here:
```bash
    while [[ "$PWD" != "/" && "$PWD" != "$home" ]]
    do
      _file="$PWD/.env"
      if [[ -e "${_file}" ]]
      then echo "${_file}"
      fi
      builtin cd ..
    done
```
Once PWD gets to `//` it stays there and keeps looping. Ran into this since my [Anaconda](https://docs.continuum.io/anaconda/) install likes to put these `//` prefixes at the start of path names. Kind of weird, but they are valid paths.

**Comment by dasJ** [comment]
Is this problem still there in 0.2.0?

In the meantime: https://www.youtube.com/watch?v=LDZX4ooRsWs

**Comment by greg9q** [comment]
Yes. Here's the loop where it get's stuck now:
```bash
		while [ "${PWD}" != "${_mountpoint}" ]; do
			_file="${PWD}/${AUTOENV_ENV_FILENAME}"
			if [ -f "${_file}" ]; then
				if [ -z "${_hadone}" ]; then
					echo -n ${_file}
					_hadone='1'
				else
					echo -n "
${_file}"
				fi
			fi
			command -v chdir >/dev/null 2>&1 && chdir .. || builtin cd ..
		done
```
Thanks much for the link.

**Comment by greg9q** [comment]
Some pertinent background:
http://stackoverflow.com/questions/20690828/what-does-double-slash-in-cd-mean-in-linux

**Comment by ashokrajar** [comment]
Need support for symlinked directory too.

Same behaviour occurs when you try to switch into a soft linked directory from other mount point.

eg: 
OS : Mac OSX
autoenv : 1.0.0
Shell : zsh

ln -s /Volumes/Disk1/code /Users/ashokraja/code
cd /Users/ashokraja/code/autoenv

df /Users/ashokraja/code
++ awk 'END{print $NF}'
+ _mountpoint=/Volumes/MDRIVE
++ _hadone=
++ '[' /Users/ashokraja/code '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/code/.env
++ '[' -f /Users/ashokraja/code/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users/ashokraja '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/.env
++ '[' -f /Users/ashokraja/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users '!=' /Volumes/Disk1 ']'
++ _file=/Users/.env
++ '[' -f /Users/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/Disk1 ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/MDRIVE ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
...
....
Infinite loop.

**Comment by dasJ** [comment]
@ashokrajar Can you please open a new issue for that? It's caused by another problem.

**Comment by dasJ** [comment]
@greg9q Can you please test the current master?

**Comment by greg9q** [comment]
@dasJ Yes, current master now works. Thanks!
