### ISSUE TITLE
cd /soft/link/directory/from/other/mount/point end up in Infinite Loop

### ISSUE THREAD

**Issue by ashokrajar** [kennethreitz/autoenv#133]
Need support for symlinked directory too. When you try to switch into a soft linked directory from other mount point it ends in an infinite loop and the terminal hangs until pressing ctrl + C.

eg: 
OS : Mac OSX
autoenv : 1.0.0
Shell : zsh
```
ln -s /Volumes/Disk1/code /Users/ashokraja/code
cd /Users/ashokraja/code/autoenv


df /Users/ashokraja/code
++ awk 'END{print $NF}'
++ _mountpoint=/Volumes/MDRIVE
++ _hadone=
++ '[' /Users/ashokraja/code '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/code/.env
++ '[' -f /Users/ashokraja/code/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users/ashokraja '!=' /Volumes/Disk1 ']'
++ _file=/Users/ashokraja/.env
++ '[' -f /Users/ashokraja/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' /Users '!=' /Volumes/Disk1 ']'
++ _file=/Users/.env
++ '[' -f /Users/.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/Disk1 ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
++ '[' / '!=' /Volumes/MDRIVE ']'
++ _file=//.env
++ '[' -f //.env ']'
++ command -v chdir
++ builtin cd ..
...
....
```
Infinite loop.

**Comment by dasJ** [comment]
This is really hard to solve. On linux, I can use `readlink -f` to canonicalize every symlink, but this option does not exist on darwin. Do you have any idea how to do this on darwin? As I don't have a Mac, I can not test this myself :-1:

**Comment by ashokrajar** [comment]
How about using ```pwd -P``` command ?

**Comment by dasJ** [comment]
@ashokrajar Does this work on darwin as well?

**Comment by ashokrajar** [comment]
Yup it works on darwin too. I have verified.

**Comment by dasJ** [comment]
Can you test #135 please?
