### ISSUE TITLE
autoenv is broken in zsh

### ISSUE THREAD

**Issue by Shellcat-Zero** [kennethreitz/autoenv#138]
I just installed autoenv, and after sourcing ~/.autoenv/activate.sh the shell hangs until sending interrupt signal (ctrl-C).  

I executed test.sh in the tests directory, and here is the output:
```
./test.sh 
:: Running test_not_file for bash...Success.
:: Running test_custom_filename for bash...Success.
:: Running test_symlink for bash...Success.
:: Running test_simple for bash...Success.
:: Running test_cd_spaces for bash...Success.
:: Running test_colons for bash...Success.
:: Running test_doubleslash for bash...Success.
:: Running test_cd_env for bash...Success.
:: Running test_noclobber for bash...Success.
:: Running test_auth_spaces for bash...Success.
:: Running test_not_file for zsh...
^CFail.
Fail.
:: Output of last test:

:: Output of last test:

```

**Comment by dasJ** [comment]
Which zsh version are you using?

**Comment by Shellcat-Zero** [comment]
I'm on zsh 5.0.2 (x86_64-pc-linux-gnu)

**Comment by dasJ** [comment]
Can you send me your aliases by running `alias`? (Of course, you can leave out the ones which are obviously unrelated like some git aliases)

**Comment by dasJ** [comment]
What does `which chdir` return for you?

**Comment by Shellcat-Zero** [comment]
```
which chdir
chdir: shell built-in command
```

**Comment by dasJ** [comment]
Can you send me the tracing output? Just add `set -x` to the beginning of the autoenv script.

**Comment by dasJ** [comment]
Does #142 fix this?

**Comment by Shellcat-Zero** [comment]
Hi, I'm sorry I really didn't have time to debug this, and I still don't have time to spare on this issue, but I wanted to let you know that it is still broken in zsh, this time failing at test_cd_env for zsh.

After cloning the repo and installing it, the .zshrc file cannot be sourced due to it hanging on your activate.sh script.  Output of test.sh:
```
./test.sh 
:: Running test_cd_env for bash...Success.
:: Running test_noclobber for bash...Success.
:: Running test_not_file for bash...Success.
:: Running test_doubleslash for bash...Success.
:: Running test_colons for bash...Success.
:: Running test_simple for bash...Success.
:: Running test_auth_spaces for bash...Success.
:: Running test_cd_spaces for bash...Success.
:: Running test_symlink for bash...Success.
:: Running test_custom_filename for bash...Success.
:: Running test_cd_env for zsh...^CFail.
Fail.
:: Output of last test:

:: Output of last test:
```
