### ISSUE TITLE
Leading double quote when using AUTOENV_CUR_DIR on zsh 5.2 (macOS Sierra)

### ISSUE THREAD

**Issue by johnwheeler** [kennethreitz/autoenv#150]
When I do this

```
source "$AUTOENV_CUR_DIR/venv/bin/activate"
```

I'm getting a leading double-quote (e.g. `"/Users/jwheeler/Projects/startup-starter`). It's making cd'ing into sub directories throw an error that the directory can't be found.

Here's my .env

```
echo $AUTOENV_CUR_DIR
source venv/bin/activate
```

Here's the output

```
"/Users/jwheeler/Projects/startup-starter
/Users/jwheeler/Projects/startup-starter/.env:source:2: no such file or directory: venv/bin/activate
```

Using autoenv==0.2.0

**Comment by dasJ** [comment]
Sorry, I accidentially pushed here directly. Does the current master fix it for you?

**Comment by johnwheeler** [comment]
Yes - that fixes it. Thanks. Now I can enjoy this cool utility.
