### ISSUE TITLE
Hangs when cd'ing under /Volumes on OS X 10.12

### ISSUE THREAD

**Issue by alexreg** [kennethreitz/autoenv#151]
If I `cd` to (or within) some subdirectory of `/Volumes` (this happened with an external USB drive), `autoenv` hangs, making the *Terminal* tab title flicker between `bash` and `-bash` endlessly. This only happens with *autoenv* installed and sourced in my `.bashrc`. Seems like a clear bug.

**Comment by dasJ** [comment]
Can you send us some execution trace by executing `set -x` before cding?

**Comment by alexreg** [comment]
How odd. Seems to have been a transient error… will let you know if it reappears.

**Comment by tharant** [comment]
I have experienced the same issue; it occurs if the mount point includes a space in its name, which causes `autoenv_init()` to degenerate into an infinite loop.

Here's a snippet of debug output demonstrating the problem for my `/Volumes/Storage Array` mount:

`++ df '/Volumes/Storage Array/development/fulfillment'`
`++ awk 'END{print $NF}'`
`+ _mountpoint=Array`


Assuming coreutils is installed, the `stat` utility provides a far more reliable way of getting the mount point for a given path; I'm running macOS and I've updated my `activate.sh` as follows:

`_mountpoint="`\gstat -c %m -- "${PWD}"`"`

A linux box would instead need to use:

`_mountpoint="`\stat -c %m -- "${PWD}"`"`

Perhaps you could update the project to depend upon coreutils?

**Comment by tharant** [comment]
derp; markdown fail; the relevant code should instead be:

for macOS
``_mountpoint="`\gstat -c %m -- "${PWD}"`"``

for linux
``_mountpoint="`\stat -c %m -- "${PWD}"`"``

**Comment by dasJ** [comment]
But we cannot expect everyone to have the gnu coreutils

**Comment by tharant** [comment]
Yeah, I recognize that not everyone will have `coreutils` already installed on their box.   However, the package is available for nearly all linux and bsd distros and even macOS via `homebrew`.  I was thinking that perhaps the `homebrew` package and the linux package could be made to depend upon `coreutils` so that it's automatically installed if not already present.

Alternatively, if you'd prefer to require no external dependencies, I'm happy to do some research to see if I can come up with a portable and more reliable way of getting the mountpoint for a given path.

Thanks.

**Comment by williamsmj** [comment]
This extracts everything after the sixth set of whitespace in the output of `df`, so is robust against whitespace in the mountpoint:
```bash
df -P "${PWD}" | tail -1 | awk '{ for(i=6; i<NF; i++) printf "%s",$i OFS; if(NF) printf "%s",$NF; printf ORS}'
```
e.g.
```bash
$ pwd
/Volumes/Time Machine Backups/Backups.backupdb
$ df -P "${PWD}" | tail -1 | awk '{ for(i=6; i<NF; i++) printf "%s",$i OFS; if(NF) printf "%s",$NF; printf ORS}'
/Volumes/Time Machine Backups
```

Verified working out of the box on macOS 10.12 and Ubuntu Linux. This approach depends on the `-P` switch of `df` ensuring that the mountpoint is in the 6th column. I don't have access to other systems to test but it seems to be cross-platform.

That said, personally I'm +1 for depending on coreutils. It's a standard dependency on Linux, and is trivially installable (and can be specified as a dependency) using homebrew on macOS, which is presumably how a lot of people install autoenv in the first place. Failing that, if you don't want a hard dependency you could use `stat` when it is available:

```bash
if command -v stat >/dev/null 2>&1; then  # Standard GNU coreutils systems
    _mountpoint=$(stat -c %m -- "${PWD}")
elif command -v gstat >/dev/null 2>&1; then  # macOS homebrew coreutils
    _mountpoint=$(gstat -c %m -- "${PWD}")
else  # fragile but POSIX
    _mountpoint=$(df -P "${PWD}" | tail -1 | awk '{ for(i=6; i<NF; i++) printf "%s",$i OFS; if(NF) printf "%s",$NF; printf ORS}')
fi
```
Happy to put together PRs for any of these.

**Comment by williamsmj** [comment]
Turns out that suggestion is indeed a little fragile; it breaks on mountpoints containing numbers. This might be more robust (tested working on OS X with both BSD and coreutils `df`):
```bash
df -P "${PWD}" | tail -1 | awk '{ for(i=6; i<NF; i++) printf "%s",$i OFS; if(NF) printf "%s",$NF; printf ORS}'
```

**Comment by dasJ** [comment]
I'd prefer a way without awk, even if we use it at the moment. Is there really not POSIX way to solve this problem?
I am currently thinking about parsing /proc/mounts. Does this file also exist on Darwin?

**Comment by williamsmj** [comment]
No, `/proc/mounts` is not available on Darwin (and I don't think it's POSIX).

`awk` is POSIX, for what it's worth.

**Comment by dasJ** [comment]
Does #157 fix it for you=

**Comment by williamsmj** [comment]
Yes, no regressions afaict and fixes the bug with mount points with spaces on macOS only. Haven't tested elsewhere.
