### ISSUE TITLE
cd override error after update zsh to v5.4.1

### ISSUE THREAD

**Issue by pimuzzo** [kennethreitz/autoenv#173]
Hi,
I've encountered this error after update to zsh 5.4.1 on my debian testing:
```
/home/user/.autoenv/activate.sh:1: defining function based on alias `cd'
/home/user/.autoenv/activate.sh:151: parse error near `()'
```
Any help is appreciated

**Comment by Gnouc** [comment]
@pimuzzo It's the latest feature of zsh, which through an error when you defining a function with the same name with an alias. See more details [here](http://www.zsh.org/mla/workers/2017/msg00048.html)
