### ISSUE TITLE
Can't seem to get it to work.

### ISSUE THREAD

**Issue by marcoamorales** [kennethreitz/autoenv#41]
I'm using it on a virtualenv, installed autoenv via pip and it seems to install correctly.

Inside the virtualenv, I run the example code:
````bash
$ touch project/.env
$ echo "echo 'woah'" > project/.env
$ cd project
````

and.... nothing happens :( 
I'm using zsh and I'm on Arch, not sure if this affects this is any way.
Thanks

**Comment by junejie** [comment]
This way works for me.

    $ brew install autoenv
    $ echo "source $(brew --prefix autoenv)/activate.sh" >> ~/.zshrc
    $ source ~/.zshrc

**Comment by kennethreitz** [comment]
I recommend direnv
