### ISSUE TITLE
Add a utility command for creating a new .env file

### ISSUE THREAD

**Issue by hangtwenty** [kennethreitz/autoenv#42]
Since we're interested in super duper automatic things, why not add a utility funciton to create a generic env file? For example, it could determine the present working directory, then create a file `.env` with the contents `use_env <pwd>`.

Something like `autoenv_new`. Then users could alias it to `newenv` or even `.env`.

**Comment by dasJ** [comment]
I don't really see a point in this. Maybe it's just obsolete now.
