### ISSUE TITLE
Compatibility with .rvmrc

### ISSUE THREAD

**Issue by RobertLowe** [kennethreitz/autoenv#45]
Hey,

After `brew install autoenv` my `.rvmrc` broke.

Both tools compete for overriding `cd`, any ideas on this?

**Comment by wbyoung** [comment]
A better option that's compatible with both [`rvm` >= 1.25.27](https://github.com/rvm/rvm) and [`avn` >= 0.1.3](https://github.com/wbyoung/avn):

Add the following to your `.bash_profile`:

```bash
# add autoenv functionality (compatible with rvm & avn)
function __autoenv_chpwd() { autoenv_init; }
[[ " ${chpwd_functions[*]} " == *" __autoenv_chpwd "* ]] ||
  chpwd_functions+=(__autoenv_chpwd)
```

**Comment by sbliven** [comment]
@wbyoung Can you explain a bit what your script does? Does this replace sourcing activate.sh?

**Comment by wbyoung** [comment]
@sbliven this uses the `chpwd_functions` feature of `zsh` to integrate with `cd`. If you're using `bash`, `rvm` has a small bash "library" that was extracted into [`mpapis/bash_zsh_support`](https://github.com/mpapis/bash_zsh_support) which allows these `cd` overrides to be defined using the same `chpwd_functions` that's available in `zsh`. Loading either `avn` or `rvm` before defining the above would get you that interop "library".

`autoenv` does not use `chpwd_functions`, but feel free to 👍  #92. This little hack above is _not_ a replacement to sourcing `activate.sh`. You should add it after sourcing that. It unsets the override of `cd` after defining a function to [execute the necessary `autoenv` stuff](https://github.com/kennethreitz/autoenv#disclaimer) during the `chpwd` hook.
