### ISSUE TITLE
Add a new tag with an updated version

### ISSUE THREAD

**Issue by carloscheddar** [kennethreitz/autoenv#61]
I was using homebrew to install the package but the version is from 2 years ago(0.1.0).
If I edit the formula to always link to the master then that may cause problems in the future.

**Comment by immerrr** [comment]
I'd like to bump this for visibility.

I have just installed autoenv following the README (pip install autoenv) and got version 1.0.0, which is rather fresh yet still seems lacking a few niceties of the current master.

**Comment by dasJ** [comment]
Before tagging a new release, I'd like to make sure the codebase is stable. I'm currently writing some tests to ensure that some things are working and I'd like to close some github issues before.

**Comment by dasJ** [comment]
We are actually really close to a new release. Once the dash support works in zsh 5.1, and @kennethreitz has verified that the code works, we can publish a new release.

**Comment by dasJ** [comment]
It is done! PR for Homebrew is at https://github.com/Homebrew/homebrew-core/pull/3705
