### ISSUE TITLE
autoenv executes even in subfolder

### ISSUE THREAD

**Issue by fizerkhan** [kennethreitz/autoenv#63]
Python project's top folder has `.env` file with following contents

      source venv/bin/activate

This command executed whenever `cd` to any sub folder of the project. Then throws

      -bash: venv/bin/activate: No such file or directory

Why it executes even in subfolder?

**Comment by bjorgvino** [comment]
I'm using the following `.env` script to prevent the environment from being activated again on every `cd`:

```shell
venv=<environment>
currentvenv=""
 
if [[ $VIRTUAL_ENV != "" ]]
then
  # Strip out the path and just leave the env name
  currentvenv="${VIRTUAL_ENV##*/}"
fi
 
if [[ "$currentvenv" != "$venv" ]]
then
  echo "Switching to environment: $venv"
  workon $venv
#else
#  echo "Already on environment $venv"
fi
```

See:
https://gist.github.com/bjorgvino/455618ecbc1536bb3333

**Comment by wikibootup** [comment]
currentvenv="${VIRTUAL_ENV}"

if [[ "$currentvenv" != "/usr/local/opt/pyenv/versions/your_pyenv_virtualenv" ]]
then
  pyenv activate yebimom
fi

**Comment by chhantyal** [comment]
Thanks @satyrius for workaround. That seems to work.

**Comment by edyan** [comment]
Hi, 

Thanks, personally I have adapted your answers for another type of solution. Maybe that could help:
`
FILE='.env' # a file that is present only at the root directory
if [ -z "$VIRTUAL_ENV" -a -f .env ]; then
    echo "Activating that virtualenv"
    source virtualenv/bin/activate
elif [ -z "$VIRTUAL_ENV" ]; then
    echo "If you want to activate your virtualenv you need to go to the root directory"
fi
`

**Comment by dasJ** [comment]
Just make the path absolute like this:
`source "$AUTOENV_CUR_DIR/venv/bin/activate"`

**Comment by zsiegel92** [comment]
Hey, @bjorgvino's solution is a good one that I have used with autoenv several times with good experiences. If anyone has this same same frustration with Conda environments, here is the equivalent. Add this to your .env file:
```
venv=<Write your conda environment name here (without angle braces)>
currentvenv=""
if [[ $CONDA_PREFIX != "" ]]
then
  # Strip out the path and just leave the env name
  currentvenv="${CONDA_PREFIX##*/}"
fi
if [[ "$currentvenv" != "$venv" ]]
then
  echo "Switching to environment: $venv"
  #workon $venv
  source activate $venv
else
  echo Still in Conda environment $venv
fi
```
I also like to add these lines to my .env to avoid having to type `source activate <environment name>`, and allow me to instead just type `activate` (same for `deactivate`):
```
activate() {
  source activate $venv
}
deactivate() {
  source deactivate $venv
}
```

**Comment by HSin-Tse** [comment]
currentvenv=`dirname ${BASH_SOURCE}`

if [[ "$currentvenv" != "$VIRTUAL_ENV" ]] &&  [[ "$currentvenv" == "$PWD" ]]
then
    source ./bin/activate
fi

**Comment by andybrnr** [comment]
I was trying to implement a conda autoenv solution along the lines of @zsiegel92, but when autoenv executes the .env file, it can't pick up the $CONDA_PREFIX environment variable (guess it's being executed by the system, so the current env variables in the terminal are unavailable)... did I do something wrong when configuring autoenv, or is there something obvious I'm missing?

**Comment by MrNinja** [comment]
Thank @edyan!

This is my solution base on @edyan supported solution:

`.env` file.
```
# Setting place
pyenv=msd_od
activatecmd=/Users/rikimaru/.pyenv/versions/anaconda3-2.2.0/envs/msd_od/bin/activate

# Prepare current environment code
currentvenv=""
if [[ $CONDA_PREFIX != "" ]] then
  # Strip out the path and just leave the env name
  currentvenv="${CONDA_PREFIX##*/}"
fi

# Check activate environment
if [[ "$currentvenv" != "$pyenv" ]] then
  echo "Switching to environment '$pyenv'"
  source $activatecmd $pyenv
else
  echo "Still in Conda environment '$pyenv'"
fi
```

**Comment by MrNinja** [comment]
Thank @edyan!

This is my solution base on @edyan supported solution:

`.env` file.
```
# Setting place
pyenv=env_name
activatecmd=/Users/rikimaru/.pyenv/versions/anaconda3-2.2.0/envs/project/bin/activate

# Prepare current environment code
currentvenv=""
if [[ $CONDA_PREFIX != "" ]] then
  # Strip out the path and just leave the env name
  currentvenv="${CONDA_PREFIX##*/}"
fi

# Check activate environment
if [[ "$currentvenv" != "$pyenv" ]] then
  echo "Switching to environment '$pyenv'"
  source $activatecmd $pyenv
else
  echo "Still in Conda environment '$pyenv'"
fi
```
