### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by asmeurer** [kennethreitz/autoenv#64]
Is there a way to use a global env configuration with this? I don't want to pollute various directories with `.env`, and having a global `~/.autoenv.yaml` or whatever would be much easier for me to track in my dotfiles repo and sync across computers.

**Comment by dasJ** [comment]
Yes, I agree with @sirajulm, this is the best approach. Putting yaml logic (or anything like this) into autoenv would make the project too complex.

**Comment by asmeurer** [comment]
I was actually (somewhat lazily) waiting for this issue to be fixed to use autoenv (lazy in the sense that for now I just do things the old fashioned way). This way seems about as hacky as just forking autoenv and doing it the right way (again, though, I'm lazy, so I doubt it will happen).
