### ISSUE TITLE
re-write test and error with 'dtf' gem

### ISSUE THREAD

**Issue by pravj** [kennethreitz/autoenv#67]
as currently `autoenv` uses `dtf` gem's `version 0.1.2`, this version is **yanked**
see here https://rubygems.org/gems/dtf/versions
I got installation error when I tried with this version, then I changed the version in code.

I am just thinking, why not write tests from scratch in bash itself.

**Comment by dasJ** [comment]
Rewritten, see 5b2a81274cf4ab7c4f966eafca66aab77cfb18a9
