### ISSUE TITLE
pip installing also needs source, but documentation does not state it

### ISSUE THREAD

**Issue by peterlauri** [kennethreitz/autoenv#70]
Installed into my system python using pip, and of course I needed to source the activate.sh file, but this is not mentioned in the README.md. Maybe it would be nice for novice users that it needs to be sourced. Of course, the location depends on where pip installs it. For me, on Mac it is:

/usr/local/bin/activate.sh

**Comment by mmautner** [comment]
:+1: @MatthewTanner, I'm using pip
