### ISSUE TITLE
How to uninstall autoenv?

### ISSUE THREAD

**Issue by oshihirii** [kennethreitz/autoenv#72]
Hello,

I installed autoenv on Linux Mint 17 with:

    $ git clone git://github.com/kennethreitz/autoenv.git ~/.autoenv
    $ echo 'source ~/.autoenv/activate.sh' >> ~/.bashrc

Can you please tell me how to unstinstall and remove related files?

I see there is folder and files now in `Home > .autoenv`.  

Thank You.

**Comment by Godsing** [comment]
If the `~/.autoenv_authorized` file cannot be found, you can use the following two commands to locate the files where autoenv records authorization information:
```bash
echo "AUTOENV_AUTH_FILE: ${AUTOENV_AUTH_FILE:-unset}"
echo "AUTOENV_NOTAUTH_FILE: ${AUTOENV_NOTAUTH_FILE:-unset}"
```
