### ISSUE TITLE
Remove that awesome gif

### ISSUE THREAD

**Issue by adelevie** [kennethreitz/autoenv#73]
Seriously. I can't stop looking at the README.

**Comment by bashu** [comment]
BTW, who is he?

**Comment by jeffbr13** [comment]
Tim and Eric's ["The Universe"](https://www.youtube.com/watch?v=NFTaiWInZ44)

**Comment by kennethreitz** [comment]
![](https://camo.githubusercontent.com/92a0e6c8cfa3aae0e70f442fc915263ee59bf5bf/687474703a2f2f6d656469612e74756d626c722e636f6d2f74756d626c725f6c74757a6a766251364c31717a677078392e676966)
