### ISSUE TITLE
how to use it to configure the specific python version to use

### ISSUE THREAD

**Issue by ohadpartuck** [kennethreitz/autoenv#75]
saw that it's using the .env file to make a virtual env. How do i specify python version as well

**Comment by GabLeRoux** [comment]
With `virtualenvwrapper`, you can create a virtualenv that uses python 3
`mkvirtualenv --python=$(which python3) name_of_environment`
then, 
`echo "workon name_of_environment" > .env`

In my case, I couldn't manage to make `autoenv` to work, but if autoenv runs `source .env`, then, it should work.
