### ISSUE TITLE
Incorrect install instructions for OSX in the README

### ISSUE THREAD

**Issue by henrahmagix** [kennethreitz/autoenv#78]
`/usr/local/opt/autoenv/activate.sh` does not exist when installed via brew (for me at least). Also, if a user has installed brew into a different location, the path to autoenv may be different and `brew --prefix` should be used.

`$(brew --prefix autoenv)/activate.sh` should always be the correct path.

**Comment by dasJ** [comment]
Fixed in a9d834eb540de1c50b5027b88c52572ba7e2a75a

**Comment by henrahmagix** [comment]
👍  Thanks!
