### ISSUE TITLE
Change without .env file

### ISSUE THREAD

**Issue by lovato** [kennethreitz/autoenv#79]
I did some research on it in the past, and I am now using a bash script I made, which achieves autoenv activation with or without .env file, by replacing cd command, the same way you do.

I made this script picking code from everywhere, and combining them together.

Please, take a look and perhaps you can think of something to improve autoenv.
I use .envs a lot, but sometimes I just forget to create.

https://gist.github.com/lovato/9913038

I wrote a tool to generate a python tree structure (basically CookieCutter does a bigger job) and this tool already creates the .env file. https://github.com/lovato/machete

Best,
Lovato

**Comment by lovato** [comment]
I have to confess that my auto-env-switcher sometimes crashes, and stop exiting the virtualenv. Still dont  know why...

**Comment by dasJ** [comment]
Thank you! :+1:
