### ISSUE TITLE
Make work with virtualenvwrapper

### ISSUE THREAD

**Issue by neverfox** [kennethreitz/autoenv#80]
I'm not sure if this is a problem with my setup or if it's just a limitation, but it would be nice if I could get autoenv source the `.env` when I use `workon` from virtualenvwrapper to change to a project directory. As it is, I have to `cd ..` and then `cd` back in to trigger autoenv.

**Comment by bdemers** [comment]
quick and dirty work around, add 'workon' to the cd function in activate.sh:
```
cd() {
  workon $(autoenv_cd "$@")
}
```

This isn't a permanent solution...

**Comment by kdeldycke** [comment]
> Or... thinking about it again, I guess I could just put workon myenv in the .env file

That's exactly what I did in my dotfiles. See: https://github.com/kdeldycke/dotfiles/blob/e397bf0941e95d0c83a36e02b4265ae2a56b8ad6/.virtualenv/postmkvirtualenv#L4-L7

**Comment by dasJ** [comment]
So does it work now?
