### ISSUE TITLE
Doesn't work when path to directory has spaces.

### ISSUE THREAD

**Issue by jervill** [kennethreitz/autoenv#81]
Bad form on my part to have spaces, but I think this should probably be fixed. Autoenv doesn't seem to work when the path to the working directory has spaces.

If the pwd is "/Users/me/my project/", I'd get an error like:
`shasum: project/.env:`
`autoenv_check_authz_and_run:source:19: no such file or directory: project/.env`
`shasum: /Users/me/my`
`autoenv_check_authz_and_run:source:19: no such file or directory: /Users/me/my`

**Comment by haggen** [comment]
+1

**Comment by thijsvandien** [comment]
+1

**Comment by dasJ** [comment]
This is already fixed (see  the tests) and will be in the next version.
