### ISSUE TITLE
Updating Homebrew formula

### ISSUE THREAD

**Issue by pikeas** [kennethreitz/autoenv#82]
I opened a PR at https://github.com/Homebrew/homebrew/pull/39777/files#r30395826, but they want a "tagged, stable release". Could you add a tag for version 1.0.0?

**Comment by pikeas** [comment]
Bump, would really like to get this into Homebrew (https://github.com/Homebrew/homebrew/pull/39777).

**Comment by jayqi** [comment]
Bumping as this is still an issue. 

For those who find this thread and still would like to install using Homebrew, the suggested workaround in the [Homebrew PR thread](https://github.com/Homebrew/homebrew/pull/39777) to install the latest version is: `brew install --HEAD autoenv`

**Comment by kennethreitz** [comment]
I will get to this soon!

**Comment by kennethreitz** [comment]
Feel free to comment here if there's no progress within the next few days (I'll get re-notified).

**Comment by pikeas** [comment]
Bump!

**Comment by kennethreitz** [comment]
Damnit! :)

**Comment by bartiaco** [comment]
Double bump. <3

**Comment by harrislapiroff** [comment]
Bump bump. 😇

**Comment by dasJ** [comment]
Duplicate of #61
