### ISSUE TITLE
How to get the path of the current .env file?

### ISSUE THREAD

**Issue by diegobernardes** [kennethreitz/autoenv#83]
I'm using autoenv with gvm(golang) and there is a command that i must execute only once to create a symlink.
How can i get the path of the .env file? If i get this, i can check inside the gvm if the link is created.

**Comment by noh4ck** [comment]
+1 to this

**Comment by kennethreitz** [comment]
ah, interesting. What do you think that command would be called?

**Comment by c960657** [comment]
With Bash, you can use `$BASH_SOURCE`:

```
echo Current .env file is ${BASH_SOURCE[0]}
```

Would be nice with a cleaner approach, though, e.g. exposing some vars such as `$AUTOENV_CUR_FILE` and `$AUTOENV_CUR_DIR`.

**Comment by kennethreitz** [comment]
`$AUTOENV_CUR_FILE` and `$AUTOENV_CUR_DIR` are now available in master!
