### ISSUE TITLE
Fails on install

### ISSUE THREAD

**Issue by richburdon** [kennethreitz/autoenv#86]
brew install autoenv
    source /usr/local/opt/autoenv/activate.sh

    -bash: /usr/local/opt/autoenv/activate.sh: line 115: syntax error near unexpected token `('
    -bash: /usr/local/opt/autoenv/activate.sh: line 115: `cd() {'

**Comment by jareware** [comment]
Got this as well after install, due to using [scm_breeze](https://github.com/ndbroadbent/scm_breeze) which also wraps `cd` by default. Since I don't really have use for its wrapper, I just removed it from the default list of wrapped commands in `~/.git.scmbrc`:

```
scmb_wrapped_shell_commands="vim emacs gedit cat rm cp mv ln cd"
```

Hope this helps.

**Comment by dasJ** [comment]
Can you give me the output of `which cd`?
