### ISSUE TITLE
Segfaults when used with ZSH 5.1

### ISSUE THREAD

**Issue by vwong** [kennethreitz/autoenv#87]
I refer to https://github.com/robbyrussell/oh-my-zsh/issues/4346#issuecomment-147018190, which discusses a crash when using autoenv in ZSH (specifically with oh-my-zsh also).

Do you think you can provide the fix suggested there?

**Comment by mcgeeco** [comment]
Ahhh so this is what's happening. This was driving me crazy. By the way, have you noticed that if you open a new shell it doesn't happen anymore? That is, cd'ing to a directory with a .env, then autocomplete - crash. But, open a new zsh first, then do the above - no crash.

**Comment by vwong** [comment]
I applied essentially the same temporary fix as you did.  Waiting for an official fix.

**Comment by vonpupp** [comment]
I'm having the same issue here. I will try to apply your temporary solutions.

**Comment by achimnol** [comment]
Oh, :+1: for the temporary fix for me, too!

**Comment by kennethreitz** [comment]
Hmmmm, I use Zsh and oh-my-zsh, and have no problems. 

What was your installation method?

**Comment by vwong** [comment]
For what it's worth, the crashes seem to have stopped with ZSH 5.2 (ArchLinux), and no special fixes are needed anymore.

**Comment by patrys** [comment]
Just hit the same problem, Fedora 23, zsh 5.1.1. Can't upgrade zsh as 5.2 will only hit Fedora 24.

**Comment by patrys** [comment]
It seems to work fine if I add `set +a` immediately after the env file is sourced.

**Comment by petruisfan** [comment]
Any news on this issue? It's affecting me on ubuntu desktop 16.04 with latest oh-my-zsh :(

**Comment by kennethreitz** [comment]
If this is to be solved, it will have to be via a contributor! I have no issues over here, using zsh (not sure which version).

**Comment by dasJ** [comment]
It should work when adding this line after the source line:
```
[ "${ZSH_VERSION}" = "5.1" ] && set +a
```
Can anyone with zsh 5.1 confirm? It works great with 5.2

**Comment by matatk** [comment]
I'm experiencing this problem on zsh 5.2, though I get a crash *any* time I change directory, regardless of whether the directory has an `.env` file. I uninstalled autoenv and the crashes stopped.  Is anyone else experiencing this problem with zsh 5.2?

**Comment by matatk** [comment]
P.S. I was just able to confirm on another machine that the problem started with version 0.2.1 of autoenv (which has recently come through via Homebrew on the Mac).

**Comment by matatk** [comment]
Some further info: I have the following zsh 'change directory hook' installed for autoenv.

```zsh
chpwd_functions=(${chpwd_functions[@]} "autoenv_init")
```

This is because I have a custom `cd` command that overrides the default one. My custom one in turn, calls `builtin cd`, which bypasses autoenv, hence the need for the hook, above.  When I disable my own custom `cd` function, autoenv 0.2.1 still triggers a crash.  However version 0.2.0 works fine either with or without my custom `cd` function.

I found a [possible related change between autoenv 0.2.0 and 0.2.1](https://github.com/kennethreitz/autoenv/compare/v0.2.0...v0.2.1#diff-561ca69c1c2aa08da999bd30d3ab8921L136) - maybe some circular reference to has come about because of this?

**Comment by dasJ** [comment]
Oh and dump the aliases as well, just to be sure there are no conflicts

**Comment by dasJ** [comment]
Can you send me an execution trace?

Something like zsh -xc 'cd /home'

**Comment by matatk** [comment]
@dasJ Thanks. I am a bit new to this, but I think I have something of potential use.  I tried `zsh -xc 'cd /home'` but oddly all I get then is:

```
➜  ~ zsh -xc 'cd /home'
+zsh:1> cd /home
➜  ~ 
```

I then tried launching an interactive shell with `zsh -x` and got a lot of output as it started up. The first time I run `cd /home` it actually works (oddly). There is *a lot* of output (596K worth in fact) but it is very repetitive; here is the end...

```
. . .
+auto_env:1> autoenv_init
+autoenv_init:1> local _mountpoint _files _orderedfiles _sedregexp _pwd
+autoenv_init:2> [ 15.4.0 '!=' darwin15.4.0 ']'
+autoenv_init:3> _sedregexp=-E 
+autoenv_init:7> _mountpoint=+autoenv_init:7> df /home
+autoenv_init:7> _mountpoint=+autoenv_init:7> awk 'END{print $NF}'
+autoenv_init:7> _mountpoint=/home 
+autoenv_init:9> _pwd=+autoenv_init:9> echo /home
+autoenv_init:9> _pwd=+autoenv_init:9> sed -E s:/+:/:g
+autoenv_init:9> _pwd=/home 
+autoenv_init:10> command -v chdir
+autoenv_init:10> chdir /home
+auto_env:1> autoenv_init
+autoenv_init:1> local _mountpoint _files _orderedfiles _sedregexp _pwd
+autoenv_init:2> [ 15.4.0 '!=' darwin15.4.0 ']'
+autoenv_init:3> _sedregexp=-E 
+autoenv_init:7> _mountpoint=+autoenv_init:7> df /home
+autoenv_init:7> _mountpoint=+autoenv_init:7> awk 'END{print $NF}'
+autoenv_init:7> _mountpoint=/home 
+autoenv_init:9> _pwd=+autoenv_init:9> echo /home
+autoenv_init:9> _pwd=+autoenv_init:9> sed -E s:/+:/:g
+autoenv_init:9> _pwd=/home 
+autoenv_init:10> command -v chdir
+autoenv_init:10> chdir /home
+auto_env:1> autoenv_init
+autoenv_init:1> local _mountpoint _files _orderedfiles _sedregexp _pwd
+autoenv_init:2> [ 15.4.0 '!=' darwin15.4.0 ']'
+autoenv_init:3> _sedregexp=-E 
+autoenv_init:7> _mountpoint=+autoenv_init:7> df /home
+autoenv_init:7> _mountpoint=+autoenv_init:7> awk 'END{print $NF}'
+autoenv_init:7> _mountpoint=/home 
+autoenv_init:9> _pwd=+autoenv_init:9> echo /home
+autoenv_init:9> _pwd=+autoenv_init:9> sed -E s:/+:/:g
+autoenv_init:9> _pwd=/home 
+autoenv_init:10> command -v chdir
+autoenv_init:10> chdir /home
+auto_env:1> autoenv_init
+autoenv_init:1> local _mountpoint _files _orderedfiles _sedregexp _pwd
+autoenv_init:2> [ 15.4.0 '!=' darwin15.4.0 ']'
+autoenv_init:3> _sedregexp=-E 
+autoenv_init:7> _mountpoint=+autoenv_init:7> df /home
+autoenv_init:7> _mountpoint=+autoenv_init:7> awk 'END{print $NF}'
+autoenv_init:7> _mountpoint=/home 
+autoenv_init:9> _pwd=+autoenv_init:9> echo /home
+autoenv_init:9> _pwd=+autoenv_init:9> sed -E s:/+:/:g
+autoenv_init:9> _pwd=/home 
➜  ~ 
```

Seems like `autoenv_init` is being called too many times, possibly recursively somehow.

When I issue `cd /home` a second time, I get no output, and then this:

    zsh: segmentation fault  zsh -x

It also behaves exactly the same if I issue `/home` (therefore bypassing my custom `cd` function).  In fact, I now realise that I didn't mention before, but I have zsh's `auto_cd` option set (i.e. so typing a directory name changes to that directory) - perhaps that is something to do with all of this.

I did try to list out all my aliases with `zsh --aliases` but I got no output at all.

This maybe isn't enough information for you to go on; if you are able to look into it further, please let me know what else you might need. Thanks again.

**Comment by dasJ** [comment]
To me, the problem seems to be this line:

```
command -v chdir >/dev/null 2>&1 && \chdir "${_pwd}" || builtin cd "${_pwd}"
```

It cds and I assume your `chpwd_functions` are run then (even after I explicitly told ZSH not to use aliases).
Does it work without your `chpwd_functions` and with just sourcing autoenv?

**Comment by matatk** [comment]
@dasJ: if I comment out `chpwd_functions` (but still source autoenv in zshrc) then it no longer triggers the segfault, even if I manually call `autoenv_init` after changing directory. (I still have the zsh option `auto_cd` set.)

**Comment by dasJ** [comment]
autoenv is not designed to be used as a `chpwd_function` because it needs to execute cd to work properly which results in a infinite loop.

**Comment by matatk** [comment]
@dasJ: thanks for the information. From your message, it seems that autoenv should *never* have worked as a `chpwd_function` but, for some reason, it did work for me, up until 0.2.1. I'm wondering what changed between 0.2.0 and 0.2.1 to cause this. I assume that I will be able to call autoenv 'manually' from my custom `cd` command; will try that. Thanks again.

**Comment by matatk** [comment]
@dasJ: I realised that my custom `cd` is not the problem here; the problem seems to be that, since 0.2.1, autoenv is incompatible with zsh's `auto_cd` option.  I've had a look at the [changes between 0.2.0 and 0.2.1](https://github.com/kennethreitz/autoenv/compare/v0.2.0...v0.2.1) but I can't figure out what might have caused this (I thought it might be the change to using `\chdir` instead of `chdir` but that alone doesn't seem to be the cause).

Do you think there will be any further versions of autoenv that work with zsh's `auto_cd` option? (It seems like you are saying above that it only happened to work by chance until now.)
