### ISSUE TITLE
"This is the first time you are about to source..." every single time

### ISSUE THREAD

**Issue by mhuggins** [kennethreitz/autoenv#88]
Every time I enter a folder containing a `.env` file, I am prompted with "This is the first time you are about to source /Users/mhuggins/Development/project/.env".  I answer "Y" every time, and the next time I enter that folder, I'm prompted again.  How can I stop this behavior?

**Comment by gorbiz** [comment]
Same here :/.

**Comment by mhuggins** [comment]
I think it's rvm related.  I ended up uninstalling autoenv and using a custom shell script.

**Comment by gorbiz** [comment]
I'm not using `rvm` though (using `nvm` but I don't think it is involved at all in my chase).

**Comment by gorbiz** [comment]
Sorry, tired over here.
I'm using `rvm`; it could be the same issue.

**Comment by gorbiz** [comment]
Embarased; my fault was constantly answering `Y` instead of `y` here:
![image](https://cloud.githubusercontent.com/assets/207850/11345155/a0726af8-9215-11e5-88af-5f5f273bc023.png)
(So, it never worked & `.env` was never sourced).
:flushed:

**Comment by mhuggins** [comment]
Wait...it's case sensitive???  Usually the capitalized option is simply to denote the default value.  That might have been my issue, though really I think autoenv should accept either option regardless of case.

**Comment by gorbiz** [comment]
:+1: Thanks man, reduced confusion FTW! :)

**Comment by mhuggins** [comment]
Closing since #93 was merged.
