### ISSUE TITLE
does not work with spaces in the path

### ISSUE THREAD

**Issue by simondh** [kennethreitz/autoenv#89]
cd ~
   mkdir my\ dir
   ls
   cd my\ dir/
   echo "ls -al" > .env
   cd ..
   cd my\ dir/
   cd ..
   cd my\ dir/

I get:
/Users/simon/my dir
shasum: dir/.env:
-bash: dir/.env: No such file or directory
shasum: /Users/simon/my:
-bash: /Users/simon/my: No such file or directory

cheers

**Comment by carlmjohnson** [comment]
Came here to add the same.

**Comment by adriancooney** [comment]
Yep, just had the same issue!

**Comment by carlmjohnson** [comment]
This duplicates https://github.com/kennethreitz/autoenv/issues/81

The issue is fixed on master. Unfortunately, there hasn't been a published version since the fix, so you can't install it with Homebrew or pip, only by manually cloning the repo.

**Comment by kennethreitz** [comment]
@carlmjohnson soon :)
