### ISSUE TITLE
Invalid Option Name

### ISSUE THREAD

**Issue by kheaactua** [kennethreitz/autoenv#90]
I installed autoenv, but I get the following whnever I try to use it

```sh
gmp13@dena:CONT10km$ cd GEM
-bash: set: [01: invalid option name
bash: 31mallexport: command not found...
```

My shell is bash, I activated it, etc.. I was asked to accept the `.env` file:
```sh
autoenv:
autoenv: WARNING:
autoenv: This is the first time you are about to source /home/gmp13/gm/experiments/dena/CONT10km/GEM/.env:
autoenv:
...
```

The contents of my `.env` file is to source a file, and that file is full of `export`s

**Comment by dasJ** [comment]
Can you check the encoding of the file? It looks like it got screwed up.

**Comment by marcevrard** [comment]
I get a similar message on my installation (macOS 10.12.1) each time I use the `cd` command:
```bash
-bash: set: nvalid option name
-bash: 35: command not found
-bash: 40mallexport: command not found
```
I try both the version 0.2.1 and  the --HEAD version of autoenv, they yield the same.

**Comment by dasJ** [comment]
@marcevrard That looks like the file was modified while in use. Does the problem persist after restarting all shells?

**Comment by marcevrard** [comment]
@dasJ the problem persisted after restarting the terminal.
