### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cassionandi** [kennethreitz/autoenv#91]
Is autoenv supporting Windows?

**Comment by dragon788** [comment]
On Linux the autoenv tool replaces the shell's built in `cd` function with its own cd function that enters the environment specified in the .env file.

On Windows unless using Git Bash/msys2/cygwin the `cd` function isn't as easily overridden, and autoenv is basically a shell script, so I'd imagine the reason you aren't seeing the same behavior is that the developers haven't fully implemented a batch/PowerShell version that is tested on Windows.

I am looking at using something like autoenv myself, so once I have discovered any new information I'll come back and update this. I do believe there is a PowerShell module available that does something similar, if I run into it again I'll post it here.

**Comment by dasJ** [comment]
As this is a shell script, it must run in a shell. cmd.exe and the Powershell both don't support the shell script syntax and are not supported. 

To support Windows, the entire project must be rewritten from scratch (and it wouldn't be compatible with a shell anymore). That would be a completely different project.

**Comment by aagostini-tada** [comment]
Gah, Windows

**Comment by dragon788** [comment]
Pipenv supports Windows and has autoenv-like functionality, check it out!
