### ISSUE TITLE
Compatibility with other tools

### ISSUE THREAD

**Issue by wbyoung** [kennethreitz/autoenv#92]
It'd be nice for this to support compatibility with `rvm` and `avn` out of the box to avoid having to [hack in compatibility manually](https://github.com/kennethreitz/autoenv/issues/45).

There's a [small library](https://github.com/mpapis/bash_zsh_support) that easily allows this type of compatibility and is easy to integrate.

**Comment by dasJ** [comment]
See this comment for a fix: https://github.com/kennethreitz/autoenv/issues/45#issuecomment-18232652
