### ISSUE TITLE
`autoenv_check_authz_and_run:20: = not found` when entering into a new directory with `.env` file

### ISSUE THREAD

**Issue by svetlyak40wt** [kennethreitz/autoenv#94]
I've just installed autoenv from source onto Ubuntu Trusty (commit 7858eaaf6b23a968e63fbb7584ff0df2795181ec) and it gives me this error when entering into a new directory with `.env` file:

```
autoenv:
autoenv: WARNING:
autoenv: This is the first time you are about to source /home/art/theproject/.env:
autoenv:
autoenv:     --- (begin contents) ---------------------------------------
autoenv:     # my token
autoenv:     TOKEN=*****
autoenv:
autoenv:     --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) y
autoenv_check_authz_and_run:20: = not found
```

**Comment by svetlyak40wt** [comment]
Hey, I've checked if it is work for commit c4bc3f5 (before) `9947b4a - Accept 'Y' or 'y' for prompt` was merged. And it works. Seems commit 9947b4a broke something.

**Comment by sepehr** [comment]
Nothing new on this?

**Comment by mpolakovic** [comment]
I can confirm this issue still exists (installed on Arch Linux using antigen)

**Comment by devinus** [comment]
Getting the same issue.

**Comment by SkiftCreative** [comment]
I can confirm also that on the latest release, I have the same issue. reverting to  #c4bc3f5 fixes the issue for me

**Comment by jicksta** [comment]
+1 I am getting this as well.

**Comment by kennethreitz** [comment]
Fixed! https://github.com/kennethreitz/autoenv/pull/97

**Comment by jicksta** [comment]
thanks @kennethreitz !

**Comment by devinus** [comment]
Works!
