### ISSUE TITLE
autoenv still fires off if you try and cd into a "non-configured device", or on a folder called .env

### ISSUE THREAD

**Issue by raincoats** [kennethreitz/autoenv#96]
Hi, I sort of have 2 things I've discovered about autoenv. First one is pretty straightforward, it does not seem to check if .env is a dir or file:

```
autoenv % pwd -P
/private/tmp/autoenv

autoenv % mkdir -p hello/.env

autoenv % cd hello
shasum: /tmp/autoenv/hello/.env:
..........
autoenv:     --- (begin contents) ---------------------------------------
sed: read error on /tmp/autoenv/hello/.env: Is a directory
autoenv:     --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) y
shasum: /tmp/autoenv/hello/.env:
```
I made a 10MB ext4 filesystem on a Linux computer, then copied it to my OS X laptop (10.11), mounted it and tried to `cd` into it. I was trying to test out the OS X fuse ext4 thingo. I believe I am running the newest version of `autoenv` (as it should be updating with Homebrew).

The ext4 filesystem didn't work correctly when I mounted it (ie, trying to `ls` into it gives `ls: cannot open directory /mnt: Device not configured`)

```
~ % ext4fuse ext4 /mnt

~ % cd /mnt
shasum: /mnt/.env:
.........
autoenv:     --- (begin contents) ---------------------------------------
sed: can't read /mnt/.env: Device not configured
autoenv:     --- (end contents) -----------------------------------------
..........
```

although sometimes, on that broken ext4 filesystem, it will give me "Is a directory" (but no .env directory exists?)

```
~ % umount /mnt
Unmount successful for /mnt

~ % ext4fuse ext4 /mnt

~ % cd /mnt
shasum: /mnt/.env:
......
autoenv:     --- (begin contents) ---------------------------------------
sed: read error on /mnt/.env: Is a directory
autoenv:     --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) yes

/mnt % ll
ls: cannot access sha512.sums: Input/output error
ls: reading directory .: Device not configured
4.0K drwxr-xr-x 43 root root 4.0K Dec 16 19:54 ../
 12K drwx------  2 root root  12K Dec 22 18:43 lost+found/
3.0K drwxr-xr-x 63 root root 3.0K Dec 22 18:44 etc/
1.0K drwxr-xr-x  4 root root 1.0K Dec 22 18:44 ./
307K -rw-r--r--  1 root root 307K Dec 22 18:44 sha512.sums
```

Anyway, I'm going to end this here, I don't want this issue report to look like I'm asking for help with fuse ext4, which is probably does. Just observing that it likes to activate at some odd times.

**Comment by dasJ** [comment]
This is fixed by now, and there is a test to verify this :+1:
